# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go Dev/Test(196bc91b-c467-4d8d-ab33-1d2e5b518195)'
    subscriptionId: '196bc91b-c467-4d8d-ab33-1d2e5b518195'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(ResourceGroupName)'
    location: '$(ResourceGroupLocation)'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/techtoniq/DailyJoke.Net/Resources/Azure/azuredeploy_database.json'
    overrideParameters: |
      -env "$(Env)"
      -company "$(Company)"
      -sqladminusername "$(SqlAdminUsername)"
      -sqladminpassword "$(SqlAdminPassword)"
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
